//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helicopter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControllerRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControllerRecord()
        {
            this.MeasurementRecords = new HashSet<MeasurementRecord>();
        }
    
        public int Id { get; set; }
        public int SessionId { get; set; }
        public string Name { get; set; }
        public string DriverType { get; set; }
        public double CWProportionalGain { get; set; }
        public double CWIntegralGain { get; set; }
        public double CWDerivativeGain { get; set; }
        public Nullable<double> CCWProportionalGain { get; set; }
        public Nullable<double> CCWIntegralGain { get; set; }
        public Nullable<double> CCWDerivativeGain { get; set; }
        public double IntegralWindupThreshold { get; set; }
        public int OutputRateLimit { get; set; }
    
        public virtual SessionRecord SessionRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasurementRecord> MeasurementRecords { get; set; }
    }
}
