//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helicopter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementRecord
    {
        public int Id { get; set; }
        public int ControllerId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public double SetPoint { get; set; }
        public double CurrentAngle { get; set; }
    
        public virtual ControllerRecord ControllerRecord { get; set; }
    }
}
