//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helicopter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionRecord()
        {
            this.ControllerRecords = new HashSet<ControllerRecord>();
        }
    
        public int Id { get; set; }
        public int SettingsId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Comment { get; set; }
    
        public virtual SettingsRecord SettingsRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControllerRecord> ControllerRecords { get; set; }
    }
}
