#ifndef GLOBALS_H_
#define GLOBALS_H_

#define INT_LINE_SIZE_MAX			256
#define INT_PARAMETER_COUNT_MAX		3
#define INT_PARAMETER_LENGTH_MAX	40
#define INT_DESCRIPTION_MAX			60

extern char gParameters[INT_PARAMETER_COUNT_MAX][INT_PARAMETER_LENGTH_MAX + 1];

#endif /* GLOBALS_H_ */